### ISSUE TITLE
Setting unknown property: Solspace\Freeform\Elements\Db\SubmissionQuery::primaryModel

### ISSUE THREAD

**Issue by birdkiwi** [solspace/craft3-freeform#100]
Hello again :) I'm trying to get payments with PaymentsRecord class and getting this error in the custom module.

```
yii\base\UnknownPropertyException: Setting unknown property: Solspace\Freeform\Elements\Db\SubmissionQuery::primaryModel in /app/vendor/yiisoft/yii2/base/Component.php:210
Stack trace:
#0 /app/vendor/craftcms/cms/src/elements/db/ElementQuery.php(538): yii\base\Component->__set('primaryModel', Object(Solspace\Freeform\Records\Pro\Payments\PaymentRecord))
#1 /app/vendor/yiisoft/yii2/db/BaseActiveRecord.php(450): craft\elements\db\ElementQuery->__set('primaryModel', Object(Solspace\Freeform\Records\Pro\Payments\PaymentRecord))
#2 /app/vendor/yiisoft/yii2/db/BaseActiveRecord.php(397): yii\db\BaseActiveRecord->createRelationQuery('Solspace\\Freefo...', Array, false)
#3 /app/vendor/solspace/craft-freeform/packages/plugin/src/Records/Pro/Payments/PaymentRecord.php(62): yii\db\BaseActiveRecord->hasOne('Solspace\\Freefo...', Array)
#4 /app/vendor/yiisoft/yii2/db/BaseActiveRecord.php(1244): Solspace\Freeform\Records\Pro\Payments\PaymentRecord->getSubmission()
#5 /app/vendor/yiisoft/yii2/db/ActiveQueryTrait.php(177): yii\db\BaseActiveRecord->getRelation('submission')
#6 /app/vendor/yiisoft/yii2/db/ActiveQueryTrait.php(144): yii\db\ActiveQuery->normalizeRelations(Object(Solspace\Freeform\Records\Pro\Payments\PaymentRecord), Array)
#7 /app/vendor/yiisoft/yii2/db/ActiveQuery.php(224): yii\db\ActiveQuery->findWith(Array, Array)
#8 /app/vendor/yiisoft/yii2/db/Query.php(249): yii\db\ActiveQuery->populate(Array)
#9 /app/vendor/yiisoft/yii2/db/ActiveQuery.php(133): yii\db\Query->all(NULL)
#10 /app/vendor/craftcms/cms/src/db/Paginator.php(213): yii\db\ActiveQuery->all(NULL)
#11 /app/modules/allstar/controllers/EmployeeController.php(289): craft\db\Paginator->getPageResults()
#12 [internal function]: modules\allstar\controllers\EmployeeController->actionPayments()
#13 /app/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#14 /app/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array)
#15 /app/vendor/craftcms/cms/src/web/Controller.php(190): yii\base\Controller->runAction('payments', Array)
#16 /app/vendor/yiisoft/yii2/base/Module.php(534): craft\web\Controller->runAction('payments', Array)
#17 /app/vendor/craftcms/cms/src/web/Application.php(274): yii\base\Module->runAction('allstar-module/...', Array)
#18 /app/vendor/yiisoft/yii2/web/Application.php(104): craft\web\Application->runAction('allstar-module/...', Array)
#19 /app/vendor/craftcms/cms/src/web/Application.php(259): yii\web\Application->handleRequest(Object(craft\web\Request))
#20 /app/vendor/yiisoft/yii2/base/Application.php(392): craft\web\Application->handleRequest(Object(craft\web\Request))
#21 /app/web/index.php(22): yii\base\Application->run()
#22 {main}
```

**Steps to reproduce**
1. Create module and controller
2. 
```
public function actionPayments(): string
{
    $payments = PaymentRecord::find()
            ->with('submission')
            ->orderBy('id DESC');
    $paginator = new Paginator($payments, [
            'pageSize' => 10,
            'currentPage' => Craft::$app->request->pageNum,
        ]);

        $pageResults = $paginator->getPageResults();
        $pageInfo = Paginate::create($paginator);

        return Craft::$app->getView()
            ->renderPageTemplate(
                'modulename/staff/payments.twig',
                [
                    'submissions' => $pageResults,
                    'pageInfo' => $pageInfo,
                ]
            );
```

**Expected behavior**
Get a list of payments and corresponding submissions

**Craft & Plugin Info (please complete the following information):**
 - Craft Version: 3.6.2
 - Freeform Version: 3.10.4
 - Freeform Edition: PRO
 - Fresh Install or Upgrade: Fresh

**Additional context**

**Comment by gustavs-gutmanis** [comment]
hey @birdkiwi 

this happens when there's a column in the query which doesn't exist on the `Submission` element.  
Is there a way for you to see what the query looks like?

I'm assuming that when you're finding Records using `->with()`, that's where misalignments happens.  
To be honest, FF was built before knowing all the ins and outs of craft and yii, so not everything works out of the box.

**Comment by kjmartens** [comment]
Closing due to inactivity after 1 week. If the issue persists, please let us know and we can reopen the ticket.
