### ISSUE TITLE
Internal Server Error on Quick Export: Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by romainpoirier** [solspace/craft3-freeform#110]
**Describe the bug or issue you're experiencing**
Quick Export all submissions of a form showed an Internal Server Error page from Craft CMS.

I got this in the logs:
```
2021-03-01 10:07:03 [-][1][orc20kgjoafglc7liejjmp83vu][error][yii\base\ErrorException:2] yii\base\ErrorException: Invalid argument supplied for foreach() in /solspace/craft-freeform/packages/plugin/src/Library/Export/AbstractExport.php:115
Stack trace:
#0 /craftcms/cms/src/web/ErrorHandler.php(76): yii\base\ErrorHandler->handleError()
#1 /solspace/craft-freeform/packages/plugin/src/Library/Export/AbstractExport.php(115): craft\web\ErrorHandler->handleError()
#2 /solspace/craft-freeform/packages/plugin/src/Library/Export/AbstractExport.php(31): Solspace\Freeform\Library\Export\AbstractExport->parseSubmissionDataIntoRows()
#3 /solspace/craft-freeform/packages/plugin/src/Library/Export/AbstractExport.php(47): Solspace\Freeform\Library\Export\AbstractExport->__construct()
#4 /solspace/craft-freeform/packages/plugin/src/Controllers/Pro/QuickExportController.php(292): Solspace\Freeform\Library\Export\AbstractExport::create()
#5 [internal function]: Solspace\Freeform\Controllers\Pro\QuickExportController->actionIndex()
#6 /yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#7 /yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams()
#8 /craftcms/cms/src/web/Controller.php(190): yii\base\Controller->runAction()
#9 /yiisoft/yii2/base/Module.php(534): craft\web\Controller->runAction()
#10 /craftcms/cms/src/web/Application.php(274): yii\base\Module->runAction()
#11 /craftcms/cms/src/web/Application.php(577): craft\web\Application->runAction()
#12 /craftcms/cms/src/web/Application.php(253): craft\web\Application->_processActionRequest()
#13 /yiisoft/yii2/base/Application.php(392): craft\web\Application->handleRequest()
#14 /www/htdocs/index.php(21): yii\base\Application->run()
#15 {main}
```

I finally localized the submission that were causing this error by clicking all submissions of each page, then click Export to CSV until I reach the error.

I finally found it, but failed to understand what caused this error. I switched its status, then switched it back by re-saving it, and then the errors disappears.

Any idea why? Maybe you could fix this for next release, by adding additional checks. Thanks!

**Steps to reproduce**
1. Quick Export
2. Get the Internal Server Error

**Craft & Plugin Info (please complete the following information):**
 - Craft Version: Craft Pro 3.6.6
 - Freeform Version: 3.10.8
 - Freeform Edition: Pro
 - Fresh Install or Upgrade: Upgrade

**Comment by kjmartens** [comment]
Hi @romainpoirier, sorry for the trouble, and thanks for reporting this. We have a fix for this in the Freeform 3.11 beta, which should be finished the beta period in a week or two. :)
