### ISSUE TITLE
Error in dynamic notifications ($recipients must not be accessed before initialization' )

### ISSUE THREAD

**Issue by rauwebieten** [solspace/craft3-freeform#1132]
**Describe the bug or issue you're experiencing**

We have a form with notifications, but the sending of the notifications fails, with this error:

Exception 'Error' with message 'Typed property Solspace\Freeform\Notifications\Types\Dynamic\Dynamic::$recipients must not be accessed before initialization' 
in /var/www/vendor/solspace/craft-freeform/packages/plugin/src/Notifications/Types/Dynamic/Dynamic.php:80

```
Exception 'Error' with message 'Typed property Solspace\Freeform\Notifications\Types\Dynamic\Dynamic::$recipients must not be accessed before initialization' 

in /var/www/vendor/solspace/craft-freeform/packages/plugin/src/Notifications/Types/Dynamic/Dynamic.php:80

Stack trace:
#0 /var/www/vendor/solspace/craft-freeform/packages/plugin/src/Bundles/Notifications/SendListeners/DynamicRecipients.php(43): Solspace\Freeform\Notifications\Types\Dynamic\Dynamic->getRecipients()
#1 [internal function]: Solspace\Freeform\Bundles\Notifications\SendListeners\DynamicRecipients->sendToRecipients()
#2 /var/www/vendor/yiisoft/yii2/base/Event.php(312): call_user_func()
#3 /var/www/vendor/solspace/craft-freeform/packages/plugin/src/Bundles/Notifications/NotificationsBundle.php(51): yii\base\Event::trigger()
#4 [internal function]: Solspace\Freeform\Bundles\Notifications\NotificationsBundle->sendNotifications()
#5 /var/www/vendor/yiisoft/yii2/base/Event.php(312): call_user_func()
#6 /var/www/vendor/solspace/craft-freeform/packages/plugin/src/Services/SubmissionsService.php(199): yii\base\Event::trigger()
#7 /var/www/vendor/solspace/craft-freeform/packages/plugin/src/Services/SubmissionsService.php(169): Solspace\Freeform\Services\SubmissionsService->postProcessSubmission()
#8 /var/www/vendor/solspace/craft-freeform/packages/plugin/src/controllers/SubmitController.php(45): Solspace\Freeform\Services\SubmissionsService->handleSubmission()
#9 [internal function]: Solspace\Freeform\controllers\SubmitController->actionIndex()
#10 /var/www/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#11 /var/www/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams()
#12 /var/www/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction()
#13 /var/www/vendor/craftcms/cms/src/web/Application.php(341): yii\base\Module->runAction()
#14 /var/www/vendor/craftcms/cms/src/web/Application.php(642): craft\web\Application->runAction()
#15 /var/www/vendor/craftcms/cms/src/web/Application.php(303): craft\web\Application->_processActionRequest()
#16 /var/www/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest()
#17 /var/www/web/index.php(12): yii\base\Application->run()
#18 {main}
```

**Steps to reproduce**

1. create form
2. create notifications
3. submit form

**Craft & Plugin Info (please complete the following information):**

- PHP: 8.1.27
- Craft Version: Craft Pro 4.8.1
- Freeform Version: 5.1.2
- Freeform Edition: PRO

**Comment by kjmartens** [comment]
Hi @rauwebieten,

I'm curious, is this a fresh install of Freeform 5? Or was it a migration from Freeform 4? 🙂
