### ISSUE TITLE
Moving spam to submissions from tableview creates non-fatal error

### ISSUE THREAD

**Issue by clarknelson** [solspace/craft3-freeform#1151]
**Describe the bug or issue you're experiencing**

When moving spam to submissions from the following screen throws a 500 error, but the entry is still moved to the submissions in the database. 

![CleanShot 2024-03-19 at 08 20 20](https://github.com/solspace/craft-freeform/assets/4106671/fe6a5fea-ae32-4c17-8f17-658ce234b75b)

Creates an error message in the bottom corner, which is concerning for the client.

![CleanShot 2024-03-19 at 08 22 00](https://github.com/solspace/craft-freeform/assets/4106671/1036036d-ae41-4445-bd4a-54014ba30df1)

Here's the stack trace of the error:

```
2024-03-19 13:09:29 [web.ERROR] [craft\web\twig\TemplateLoaderException] Unable to find the template “_elements/tableview/container”. {"trace":["#0 /var/www/staging_html/releases/20240319130814/vendor/craftcms/cms/src/web/twig/TemplateLoader.php(69): craft\\web\\twig\\TemplateLoader->_resolveTemplate()","#1 /var/www/staging_html/releases/20240319130814/vendor/twig/twig/src/Environment.php(264): craft\\web\\twig\\TemplateLoader->getCacheKey()","#2 /var/www/staging_html/releases/20240319130814/vendor/twig/twig/src/Environment.php(312): Twig\\Environment->getTemplateClass()","#3 /var/www/staging_html/releases/20240319130814/vendor/twig/twig/src/Environment.php(280): Twig\\Environment->load()","#4 /var/www/staging_html/releases/20240319130814/vendor/craftcms/cms/src/web/View.php(482): Twig\\Environment->render()","#5 /var/www/staging_html/releases/20240319130814/vendor/craftcms/cms/src/base/Element.php(1196): craft\\web\\View->renderTemplate()","#6 /var/www/staging_html/releases/20240319130814/vendor/craftcms/cms/src/controllers/ElementIndexesController.php(701): craft\\base\\Element::indexHtml()","#7 /var/www/staging_html/releases/20240319130814/vendor/craftcms/cms/src/controllers/ElementIndexesController.php(284): craft\\controllers\\ElementIndexesController->elementResponseData()","#8 [internal function]: craft\\controllers\\ElementIndexesController->actionPerformAction()","#9 /var/www/staging_html/releases/20240319130814/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()","#10 /var/www/staging_html/releases/20240319130814/vendor/yiisoft/yii2/base/Controller.php(178): yii\\base\\InlineAction->runWithParams()","#11 /var/www/staging_html/releases/20240319130814/vendor/yiisoft/yii2/base/Module.php(552): yii\\base\\Controller->runAction()","#12 /var/www/staging_html/releases/20240319130814/vendor/craftcms/cms/src/web/Application.php(341): yii\\base\\Module->runAction()","#13 /var/www/staging_html/releases/20240319130814/vendor/craftcms/cms/src/web/Application.php(642): craft\\web\\Application->runAction()","#14 /var/www/staging_html/releases/20240319130814/vendor/craftcms/cms/src/web/Application.php(303): craft\\web\\Application->_processActionRequest()","#15 /var/www/staging_html/releases/20240319130814/vendor/yiisoft/yii2/base/Application.php(384): craft\\web\\Application->handleRequest()","#16 /var/www/staging_html/releases/20240319130814/public/index.php(12): yii\\base\\Application->run()","#17 {main}"],"memory":45216408,"exception":"[object] (craft\\web\\twig\\TemplateLoaderException(code: 0): Unable to find the template “_elements/tableview/container”. at /var/www/staging_html/releases/20240319130814/vendor/craftcms/cms/src/web/twig/TemplateLoader.php:108)"} 
```

When clicking allow from this screen the error does not appear I believe.

![CleanShot 2024-03-19 at 08 25 25](https://github.com/solspace/craft-freeform/assets/4106671/d7f9fc73-e448-4e34-9cdb-7f45daf9a6c1)

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 4.8.3
- Freeform Version: v4.x-dev
- Freeform Edition: Pro
- Fresh Install or Upgrade: Upgrade

**Additional context**

**Comment by kjmartens** [comment]
Thanks for reporting this issue @clarknelson.

I can duplicate this in my testing as well. We'll work on a fix for it shortly. 🙂

**Comment by kjmartens** [comment]
Hi @clarknelson,

We are just circling back to this now... when I test it again, I can't reproduce it anymore. Can you confirm if this is still happening for you, and which version of Craft and Freeform you're currently using? 🙂
