### ISSUE TITLE
5.1.19: getSettingsModel() causing Migration to fail

### ISSUE THREAD

**Issue by DowleyDeveloped** [solspace/craft3-freeform#1271]
When trying to migrate via the command line, the following error is being created: 

```
Call to a member function getSettingsModel() on null
```

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 4.9.2 
- Freeform Version: 5.1.19
- Freeform Edition: Pro
- Fresh Install or Upgrade: Upgrade

**Comment by kjmartens** [comment]
Sorry for the trouble you're experiencing @DowleyDeveloped,

Can you tell me more about your setup?

1. Which exact version of Freeform did you upgrade from?
2. Was there a stack trace or anything else part of the error that you can provide?

Thanks 🙂

**Comment by DowleyDeveloped** [comment]
Hi @kjmartens 

Was updating from 5.1.16 to 5.1.19.

No other stack trace, just that error above

**Comment by kjmartens** [comment]
Thank you for that. Does upgrading directly to 5.1.18.1 instead work? 🙂 

We are continuing to investigate...

**Comment by DowleyDeveloped** [comment]
@kjmartens I'll have a try in the morning and see if that works 😄

**Comment by TUSAB-web** [comment]
Similar error, here is stack trace. Note, this happened when I deployed to staging. Seems to be working fine on local DDEV setup

```
2024-05-08 17:43:36 [web.ERROR] [Error] Call to a member function getSettingsModel() on null {"trace":["#0 /home/site/vendor/solspace/craft-freeform/packages/plugin/src/Form/Settings/Implementations/ValueGenerators/DefaultStatusGenerator.php(15): Solspace\\Freeform\\Services\\StatusesService->getDefaultStatusId()","#1 /home/site/vendor/solspace/craft-freeform/packages/plugin/src/Library/DataObjects/Form/Defaults/Categories/BaseCategory.php(55): Solspace\\Freeform\\Form\\Settings\\Implementations\\ValueGenerators\\DefaultStatusGenerator->generateValue(Object(Solspace\\Freeform\\Library\\DataObjects\\Form\\Defaults\\Categories\\Settings\\SubCategories\\DataStorage))","#2 /home/site/vendor/solspace/craft-freeform/packages/plugin/src/Library/DataObjects/Form/Defaults/Categories/BaseCategory.php(34): Solspace\\Freeform\\Library\\DataObjects\\Form\\Defaults\\Categories\\BaseCategory->__construct(Array)","#3 /home/site/vendor/solspace/craft-freeform/packages/plugin/src/Library/DataObjects/Form/Defaults/Defaults.php(27): Solspace\\Freeform\\Library\\DataObjects\\Form\\Defaults\\Categories\\BaseCategory->__construct(Array)","#4 /home/site/vendor/solspace/craft-freeform/packages/plugin/src/Models/Settings.php(312): Solspace\\Freeform\\Library\\DataObjects\\Form\\Defaults\\Defaults->__construct(Array)","#5 /home/site/vendor/solspace/craft-freeform/packages/plugin/src/Freeform.php(388): Solspace\\Freeform\\Models\\Settings->__construct()","#6 /home/site/vendor/craftcms/cms/src/base/Plugin.php(177): Solspace\\Freeform\\Freeform->createSettingsModel()","#7 /home/site/vendor/yiisoft/yii2/base/Component.php(139): craft\\base\\Plugin->getSettings()","#8 /home/site/vendor/yiisoft/yii2/di/ServiceLocator.php(77): yii\\base\\Component->__get('settings')","#9 /home/site/vendor/solspace/craft-freeform/packages/plugin/src/Services/StatusesService.php(41): yii\\di\\ServiceLocator->__get('settings')","#10 /home/site/vendor/solspace/craft-freeform/packages/plugin/src/Form/Settings/Implementations/ValueGenerators/DefaultStatusGenerator.php(15): Solspace\\Freeform\\Services\\StatusesService->getDefaultStatusId()","#11 /home/site/vendor/solspace/craft-freeform/packages/plugin/src/Library/DataObjects/Form/Defaults/Categories/BaseCategory.php(55): Solspace\\Freeform\\Form\\Settings\\Implementations\\ValueGenerators\\DefaultStatusGenerator->generateValue(Object(Solspace\\Freeform\\Library\\DataObjects\\Form\\Defaults\\Categories\\Settings\\SubCategories\\DataStorage))","#12 /home/site/vendor/solspace/craft-freeform/packages/plugin/src/Library/DataObjects/Form/Defaults/Categories/BaseCategory.php(34): Solspace\\Freeform\\Library\\DataObjects\\Form\\Defaults\\Categories\\BaseCategory->__construct(Array)","#13 /home/site/vendor/solspace/craft-freeform/packages/plugin/src/Library/DataObjects/Form/Defaults/Defaults.php(27): Solspace\\Freeform\\Library\\DataObjects\\Form\\Defaults\\Categories\\BaseCategory->__construct(Array)","#14 /home/site/vendor/solspace/craft-freeform/packages/plugin/src/Models/Settings.php(312): Solspace\\Freeform\\Library\\DataObjects\\Form\\Defaults\\Defaults->__construct(Array)","#15 /home/site/vendor/solspace/craft-freeform/packages/plugin/src/Freeform.php(388): Solspace\\Freeform\\Models\\Settings->__construct()","#16 /home/site/vendor/craftcms/cms/src/base/Plugin.php(177): Solspace\\Freeform\\Freeform->createSettingsModel()","#17 /home/site/vendor/craftcms/cms/src/base/Plugin.php(188): craft\\base\\Plugin->getSettings()","#18 /home/site/vendor/yiisoft/yii2/base/Component.php(180): craft\\base\\Plugin->setSettings(Array)","#19 /home/site/vendor/yiisoft/yii2/BaseYii.php(558): yii\\base\\Component->__set('settings', Array)","#20 /home/site/vendor/yiisoft/yii2/base/BaseObject.php(107): yii\\BaseYii::configure(Object(Solspace\\Freeform\\Freeform), Array)","#21 /home/site/vendor/yiisoft/yii2/base/Module.php(161): yii\\base\\BaseObject->__construct(Array)","#22 /home/site/vendor/craftcms/cms/src/base/Plugin.php(122): yii\\base\\Module->__construct('freeform', Object(craft\\web\\Application), Array)","#23 [internal function]: craft\\base\\Plugin->__construct('freeform', Object(craft\\web\\Application), Array)","#24 /home/site/vendor/yiisoft/yii2/di/Container.php(419): ReflectionClass->newInstanceArgs(Array)","#25 /home/site/vendor/yiisoft/yii2/di/Container.php(170): yii\\di\\Container->build('Solspace\\\\Freefo...', Array, Array)","#26 /home/site/vendor/yiisoft/yii2/BaseYii.php(365): yii\\di\\Container->get('Solspace\\\\Freefo...', Array, Array)","#27 /home/site/vendor/craftcms/cms/src/Craft.php(59): yii\\BaseYii::createObject(Array, Array)","#28 /home/site/vendor/craftcms/cms/src/services/Plugins.php(948): Craft::createObject(Array, Array)","#29 /home/site/vendor/craftcms/cms/src/services/Plugins.php(233): craft\\services\\Plugins->createPlugin('freeform', Array)","#30 /home/site/vendor/craftcms/cms/src/base/ApplicationTrait.php(1655): craft\\services\\Plugins->loadPlugins()","#31 /home/site/vendor/craftcms/cms/src/web/Application.php(110): craft\\web\\Application->_postInit()","#32 /home/site/vendor/yiisoft/yii2/base/BaseObject.php(109): craft\\web\\Application->init()","#33 /home/site/vendor/yiisoft/yii2/base/Application.php(204): yii\\base\\BaseObject->__construct(Array)","#34 [internal function]: yii\\base\\Application->__construct(Array)","#35 /home/site/vendor/yiisoft/yii2/di/Container.php(419): ReflectionClass->newInstanceArgs(Array)","#36 /home/site/vendor/yiisoft/yii2/di/Container.php(170): yii\\di\\Container->build('craft\\\\web\\\\Appli...', Array, Array)","#37 /home/site/vendor/yiisoft/yii2/BaseYii.php(365): yii\\di\\Container->get('craft\\\\web\\\\Appli...', Array, Array)","#38 /home/site/vendor/craftcms/cms/src/Craft.php(59): yii\\BaseYii::createObject(Array, Array)","#39 /home/site/vendor/craftcms/cms/bootstrap/bootstrap.php(264): Craft::createObject(Array)","#40 /home/site/vendor/craftcms/cms/bootstrap/web.php(40): require('/home/site/vend...')","#41 /home/site/wwwroot/index.php(21): require('/home/site/vend...')","#42 {main}"],"memory":2262080,"exception":"[object] (Error(code: 0): Call to a member function getSettingsModel() on null at /home/site/vendor/solspace/craft-freeform/packages/plugin/src/Services/StatusesService.php:42)"} 
```

**Comment by TUSAB-web** [comment]
Tried downgrading to 5.1.16.1 but that error comes up anyway. I type “php craft” and it just returns this error in the CLI: "Error: Call to a member function getSettingsModel() on null”.

**Comment by kjmartens** [comment]
Thank you @TUSAB-web.

We should likely have a fix available today/tomorrow (May 9, 2024). 🙂

**Comment by kjmartens** [comment]
This should be resolved now in Freeform 5.1.19.1. 🙂

**Comment by TUSAB-web** [comment]
The latest update resolved the issue for us. Thanks!

**Comment by kjmartens** [comment]
Thank you for confirming @TUSAB-web 🙂
