### ISSUE TITLE
Update hung up on migration permission

### ISSUE THREAD

**Issue by strandofgenius** [solspace/craft3-freeform#133]
Follow up from thread in the Craft discord.

Here is the error output
```sh
- m210413_104951_MigrateSubmissionPermissions
- m210416_072726_MigrateFormPermissions

Error Output:
================
Exception 'yii\base\NotSupportedException' with message 'Changes to the project config are not possible while in read-only mode.'

in /Users/michael/sites/c-lock-craft/c-lock-craft/vendor/craftcms/cms/src/services/ProjectConfig.php:488

Stack trace:
#0 /Users/michael/sites/c-lock-craft/c-lock-craft/vendor/craftcms/cms/src/services/Updates.php(151): craft\services\ProjectConfig->set('plugins.freefor...', '3.3.1', 'Update plugin s...')
#1 /Users/michael/sites/c-lock-craft/c-lock-craft/vendor/craftcms/cms/src/console/controllers/MigrateController.php(387): craft\services\Updates->setNewPluginInfo(Object(Solspace\Freeform\Freeform))
#2 [internal function]: craft\console\controllers\MigrateController->actionAll()
#3 /Users/michael/sites/c-lock-craft/c-lock-craft/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#4 /Users/michael/sites/c-lock-craft/c-lock-craft/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array)
#5 /Users/michael/sites/c-lock-craft/c-lock-craft/vendor/yiisoft/yii2/console/Controller.php(184): yii\base\Controller->runAction('all', Array)
#6 /Users/michael/sites/c-lock-craft/c-lock-craft/vendor/yiisoft/yii2/base/Module.php(534): yii\console\Controller->runAction('all', Array)
#7 /Users/michael/sites/c-lock-craft/c-lock-craft/vendor/yiisoft/yii2/console/Application.php(181): yii\base\Module->runAction('migrate/all', Array)
#8 /Users/michael/sites/c-lock-craft/c-lock-craft/vendor/craftcms/cms/src/console/Application.php(89): yii\console\Application->runAction('migrate/all', Array)
#9 /Users/michael/sites/c-lock-craft/c-lock-craft/vendor/yiisoft/yii2/console/Application.php(148): craft\console\Application->runAction('migrate/all', Array)
#10 /Users/michael/sites/c-lock-craft/c-lock-craft/vendor/yiisoft/yii2/base/Application.php(392): yii\console\Application->handleRequest(Object(craft\console\Request))
#11 /Users/michael/sites/c-lock-craft/c-lock-craft/craft(22): yii\base\Application->run()
#12 {main}
```

- Craft Version: 3.6.12.1
- Freeform Version: 3.10.11 -> 3.11.3
- Freeform Edition: Pro
- Fresh Install or Upgrade: Upgrade

**Additional context**

**Comment by gustavs-gutmanis** [comment]
Hi @strandofgenius,

Could you please take a look in the `vendor/solspace/craft-freeform/packages/plugin/src/migrations/m210413_104951_MigrateSubmissionPermissions.php` on line `81`, there should be code that looks like this. Is it present in your files?

```php
$projectConfig = \Craft::$app->getProjectConfig();
if ($projectConfig->readOnly) {
    return true;
}
```

**Comment by strandofgenius** [comment]
Immediately after running `php craft update freefrom` I got the error and checked that file and can see that code is present.

**Comment by strandofgenius** [comment]
I see now that my local environment was set on production. So I switched it to dev and got it upgraded. However should this potentially work from the command line?

**Comment by gustavs-gutmanis** [comment]
This should work from the command-line.
