### ISSUE TITLE
Failed Migration - Upgrading to Craft 5.x from 4.10.7

### ISSUE THREAD

**Issue by Gs-Joel** [solspace/craft3-freeform#1439]
### What happened?

After stepping through the upgrade instructions fro the Craft site then running 
`php craft up`
I get a migration failure for the first Freeform Migration

### Errors and Stack Trace (if available)

```shell
*** applying m240429_120039_CreateFormSitesMapTable
    > create table {{%freeform_forms_sites}} ...Exception: SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'freeform_forms_sites' already exists
The SQL being executed was: CREATE TABLE `freeform_forms_sites` (
	`id` int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`formId` int(11) NOT NULL,
	`siteId` int(11) NOT NULL,
	`dateCreated` datetime(0) NOT NULL,
	`dateUpdated` datetime(0) NOT NULL,
	`uid` char(36) NOT NULL DEFAULT '0'
) ENGINE = InnoDb DEFAULT CHARACTER SET = utf8mb4 DEFAULT COLLATE = utf8mb4_0900_ai_ci (/Users/joel/Websites/kakapo/vendor/yiisoft/yii2/db/Schema.php:676)
#0 /Users/joel/Websites/kakapo/vendor/yiisoft/yii2/db/Command.php(1325): yii\db\Schema->convertException(Object(PDOException), 'CREATE TABLE `f...')
#1 /Users/joel/Websites/kakapo/vendor/yiisoft/yii2/db/Command.php(1120): yii\db\Command->internalExecute('CREATE TABLE `f...')
#2 /Users/joel/Websites/kakapo/vendor/yiisoft/yii2/db/Migration.php(334): yii\db\Command->execute()
#3 /Users/joel/Websites/kakapo/vendor/solspace/craft-freeform/packages/plugin/src/migrations/m240429_120039_CreateFormSitesMapTable.php(13): yii\db\Migration->createTable('{{%freeform_for...', Array)
#4 /Users/joel/Websites/kakapo/vendor/craftcms/cms/src/db/Migration.php(50): Solspace\Freeform\migrations\m240429_120039_CreateFormSitesMapTable->safeUp()
#5 /Users/joel/Websites/kakapo/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(758): craft\db\Migration->up()
#6 /Users/joel/Websites/kakapo/vendor/craftcms/cms/src/console/controllers/MigrateController.php(382): yii\console\controllers\BaseMigrateController->migrateUp('m240429_120039_...')
#7 [internal function]: craft\console\controllers\MigrateController->actionAll()
#8 /Users/joel/Websites/kakapo/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#9 /Users/joel/Websites/kakapo/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#10 /Users/joel/Websites/kakapo/vendor/yiisoft/yii2/console/Controller.php(180): yii\base\Controller->runAction('all', Array)
#11 /Users/joel/Websites/kakapo/vendor/craftcms/cms/src/console/controllers/MigrateController.php(195): yii\console\Controller->runAction('all', Array)
#12 /Users/joel/Websites/kakapo/vendor/yiisoft/yii2/base/Module.php(552): craft\console\controllers\MigrateController->runAction('all', Array)
#13 /Users/joel/Websites/kakapo/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('migrate/all', Array)
#14 /Users/joel/Websites/kakapo/vendor/craftcms/cms/src/console/Application.php(91): yii\console\Application->runAction('migrate/all', Array)
#15 /Users/joel/Websites/kakapo/vendor/yiisoft/yii2/base/Controller.php(212): craft\console\Application->runAction('migrate/all', Array)
#16 /Users/joel/Websites/kakapo/vendor/craftcms/cms/src/console/Controller.php(207): yii\base\Controller->run('migrate/all', Array)
#17 /Users/joel/Websites/kakapo/vendor/craftcms/cms/src/console/controllers/UpController.php(60): craft\console\Controller->run('migrate/all', Array)
#18 [internal function]: craft\console\controllers\UpController->actionIndex()
#19 /Users/joel/Websites/kakapo/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#20 /Users/joel/Websites/kakapo/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#21 /Users/joel/Websites/kakapo/vendor/yiisoft/yii2/console/Controller.php(180): yii\base\Controller->runAction('', Array)
#22 /Users/joel/Websites/kakapo/vendor/craftcms/cms/src/console/ControllerTrait.php(89): yii\console\Controller->runAction('', Array)
#23 /Users/joel/Websites/kakapo/vendor/craftcms/cms/src/console/Controller.php(216): craft\console\Controller->traitRunAction('', Array)
#24 /Users/joel/Websites/kakapo/vendor/yiisoft/yii2/base/Module.php(552): craft\console\Controller->runAction('', Array)
#25 /Users/joel/Websites/kakapo/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('up', Array)
#26 /Users/joel/Websites/kakapo/vendor/craftcms/cms/src/console/Application.php(91): yii\console\Application->runAction('up', Array)
#27 /Users/joel/Websites/kakapo/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('up', Array)
#28 /Users/joel/Websites/kakapo/vendor/craftcms/cms/src/console/Application.php(122): yii\console\Application->handleRequest(Object(craft\console\Request))
#29 /Users/joel/Websites/kakapo/vendor/yiisoft/yii2/base/Application.php(384): craft\console\Application->handleRequest(Object(craft\console\Request))
#30 /Users/joel/Websites/kakapo/craft(13): yii\base\Application->run()
#31 {main}
*** failed to apply m240429_120039_CreateFormSitesMapTable (time: 0.008s)
```

### How can we reproduce this?

1. Install latest version of Craft 4 (currently Craft 4.10.7)
2. Update enviornment ready for Craft 5
3. Run `php craft up`

### Freeform Edition

Pro

### Freeform Version

5.5.4

### Craft Version

5.2.9

### When did this issue start?

After upgrading from older Craft version

### Previous Freeform Version

5.5.0

**Comment by Gs-Joel** [comment]
I was able to get in contact with free form Support via the support ticketing system and they were able to provide a fix.

I'll paste their response below in case anyone else has the same issue.

=======

> 
> If you already have the freeform_forms_sites table, you could clear out most of the migration file to let it pass through. So, you could do the following:
> 
> 1. Backup your site
> 2. Update your site's composer.json file to look for latest Freeform version (5.5.5).
> 3. Run composer update in your CLI. This will grab the latest available version (5.5.5) and pull those files to your server.
> 4. Open up /vendor/solspace/craft-freeform/packages/plugin/src/migrations/m240429_120039_CreateFormSitesMapTable.php
> 5. Delete most of the code inside it. The final file should look something like this:
> ```
> <?php
> 
> namespace Solspace\Freeform\migrations;
> 
> use craft\db\Migration;
> use craft\db\Query;
> use Solspace\Freeform\Library\Migrations\ForeignKey;
> 
> class m240429_120039_CreateFormSitesMapTable extends Migration
> {
>     public function safeUp(): bool
>     {
>         return true;
>     }
> }
> ```
> 6.  In your CLI, run ./craft migrate/all
> 7. It should then push that migration through and log is as completed.
>
