### ISSUE TITLE
m200203_180318_AddSpamReasonTable error

### ISSUE THREAD

**Issue by NixonGit** [solspace/craft3-freeform#169]
**Describe the bug or issue you're experiencing**

Upgrading from 3.6.1 to 3.11.8 results in a MySQL error

**Steps to reproduce**

1. Upgrade from 3.6.1 to 3.11.8

**Expected behavior**

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 3.5.19.1
- Freeform Version: 3.6.1
- Freeform Edition: Pro
- Fresh Install or Upgrade: Upgrade

**Additional context**

```
Database Exception: SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'freeform_spam_reason' already exists
The SQL being executed was: CREATE TABLE freeform_spam_reason (
id int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
submissionId int(11) NOT NULL,
reasonType varchar(100) NOT NULL,
reasonMessage text,
dateCreated datetime(0),
dateUpdated datetime(0),
uid char(36) NOT NULL DEFAULT '0'
) ENGINE=InnoDb DEFAULT CHARSET=utf8

Migration: Solspace\Freeform\migrations\m200203_180318_AddSpamReasonTable

Output:

> create table {{%freeform_spam_reason}} ...Exception: SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'freeform_spam_reason' already exists
The SQL being executed was: CREATE TABLE freeform_spam_reason (
id int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
submissionId int(11) NOT NULL,
reasonType varchar(100) NOT NULL,
reasonMessage text,
dateCreated datetime(0),
dateUpdated datetime(0),
uid char(36) NOT NULL DEFAULT '0'
) ENGINE=InnoDb DEFAULT CHARSET=utf8 (/Users/studiofour/Sites/hfoster/vendor/yiisoft/yii2/db/Schema.php:677)
#0 /Users/studiofour/Sites/hfoster/vendor/yiisoft/yii2/db/Command.php(1298): yii\db\Schema->convertException(Object(PDOException), 'CREATE TABLE f...')
#1 /Users/studiofour/Sites/hfoster/vendor/yiisoft/yii2/db/Command.php(1093): yii\db\Command->internalExecute('CREATE TABLE f...')
#2 /Users/studiofour/Sites/hfoster/vendor/yiisoft/yii2/db/Migration.php(323): yii\db\Command->execute()
#3 /Users/studiofour/Sites/hfoster/vendor/solspace/craft-freeform/packages/plugin/src/migrations/m200203_180318_AddSpamReasonTable.php(29): yii\db\Migration->createTable('{{%freeform_spa...', Array)
#4 /Users/studiofour/Sites/hfoster/vendor/craftcms/cms/src/db/Migration.php(52): Solspace\Freeform\migrations\m200203_180318_AddSpamReasonTable->safeUp()
#5 /Users/studiofour/Sites/hfoster/vendor/craftcms/cms/src/db/MigrationManager.php(232): craft\db\Migration->up(true)
#6 /Users/studiofour/Sites/hfoster/vendor/craftcms/cms/src/db/MigrationManager.php(148): craft\db\MigrationManager->migrateUp(Object(Solspace\Freeform\migrations\m200203_180318_AddSpamReasonTable))
#7 /Users/studiofour/Sites/hfoster/vendor/craftcms/cms/src/services/Updates.php(257): craft\db\MigrationManager->up()
#8 /Users/studiofour/Sites/hfoster/vendor/craftcms/cms/src/controllers/BaseUpdaterController.php(509): craft\services\Updates->runMigrations(Array)
#9 /Users/studiofour/Sites/hfoster/vendor/craftcms/cms/src/controllers/UpdaterController.php(203): craft\controllers\BaseUpdaterController->runMigrations(Array, 'restore-db')
#10 [internal function]: craft\controllers\UpdaterController->actionMigrate()
#11 /Users/studiofour/Sites/hfoster/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#12 /Users/studiofour/Sites/hfoster/vendor/yiisoft/yii2/base/Controller.php(180): yii\base\InlineAction->runWithParams(Array)
#13 /Users/studiofour/Sites/hfoster/vendor/craftcms/cms/src/web/Controller.php(190): yii\base\Controller->runAction('migrate', Array)
#14 /Users/studiofour/Sites/hfoster/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('migrate', Array)
#15 /Users/studiofour/Sites/hfoster/vendor/craftcms/cms/src/web/Application.php(274): yii\base\Module->runAction('updater/migrate', Array)
#16 /Users/studiofour/Sites/hfoster/vendor/craftcms/cms/src/web/Application.php(665): craft\web\Application->runAction('updater/migrate')
#17 /Users/studiofour/Sites/hfoster/vendor/craftcms/cms/src/web/Application.php(232): craft\web\Application->_processUpdateLogic(Object(craft\web\Request))
#18 /Users/studiofour/Sites/hfoster/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#19 /Users/studiofour/Sites/hfoster/public/index.php(21): yii\base\Application->run()
#20 {main}
```

**Comment by gustavs-gutmanis** [comment]
Hi @NixonGit,
I have added a check for the existence of said table in the migration, but the fact is that that should not have happened. Have you previously installed a newer version and then set it back to a different version maybe?

**Comment by NixonGit** [comment]
@gustavs-gutmanis I've just pulled a fresh db from our production site and the table is present there so I can only assume someone has been here before me. If the table isn't supposed to be there in 3.6.1 I can drop the table and resolve manually.

**Comment by gustavs-gutmanis** [comment]
Yeah, it shouldn't be there, that's what the migration is for - to create it. But there will be more incompatibility with the migrations if you pulled a DB which has a newer version of freeform set up.

**Comment by gustavs-gutmanis** [comment]
I'm marking this issue as closed since this is an issue specific only to your project.
