### ISSUE TITLE
Accessing /admin/freeform/submissions throws an error

### ISSUE THREAD

**Issue by sjenset** [solspace/craft3-freeform#18]
After upgrading to the latest beta and completing a form-submission in the front-end, I started seeing this error in the back-end.

The error only shows for both "All submissions" and for the form that has a submission; any form that has no submissions does not throw an error.

The data from the submission does not show up in the back-end, but it is correctly exported

```
Next Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("Illegal offset type"). in /var/www/www.moldejazz.no/vendor/craftcms/cms/src/templates/_elements/element.html:1
```
```
Stack trace:
#0 /var/www/www.moldejazz.no/vendor/craftcms/cms/src/web/twig/Template.php(51): Twig_Template->displayWithErrorHandling(Array, Array)
#1 /var/www/www.moldejazz.no/vendor/twig/twig/lib/Twig/Template.php(366): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#2 /var/www/www.moldejazz.no/vendor/craftcms/cms/src/web/twig/Template.php(32): Twig_Template->display(Array, Array)
#3 /var/www/www.moldejazz.no/storage/runtime/compiled_templates/60/60af87bb9aed6170f480324275b4bbdb6982a35157b67b358c0cbd548e1114b9.php(126): craft\web\twig\Template->display(Array)
#4 /var/www/www.moldejazz.no/vendor/twig/twig/lib/Twig/Template.php(389): __TwigTemplate_0f793673f68a403232b681359cfe4df2e409dcf047b318548d4ba8f3ab531f81->doDisplay(Array, Array)
#5 /var/www/www.moldejazz.no/vendor/craftcms/cms/src/web/twig/Template.php(51): Twig_Template->displayWithErrorHandling(Array, Array)
#6 /var/www/www.moldejazz.no/vendor/twig/twig/lib/Twig/Template.php(366): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#7 /var/www/www.moldejazz.no/vendor/craftcms/cms/src/web/twig/Template.php(32): Twig_Template->display(Array, Array)
#8 /var/www/www.moldejazz.no/storage/runtime/compiled_templates/17/17622d2c80c6740d9541f2f4e4a1f494841247850ce618152c22bf741b971a8e.php(77): craft\web\twig\Template->display(Array)
#9 /var/www/www.moldejazz.no/vendor/twig/twig/lib/Twig/Template.php(389): __TwigTemplate_ecf5dcea59fa7ed607b7eb367404ff18f305e4cc3ca3cc1a187857821cb82ef4->doDisplay(Array, Array)
#10 /var/www/www.moldejazz.no/vendor/craftcms/cms/src/web/twig/Template.php(51): Twig_Template->displayWithErrorHandling(Array, Array)
#11 /var/www/www.moldejazz.no/vendor/twig/twig/lib/Twig/Template.php(366): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#12 /var/www/www.moldejazz.no/vendor/craftcms/cms/src/web/twig/Template.php(32): Twig_Template->display(Array, Array)
#13 /var/www/www.moldejazz.no/vendor/twig/twig/lib/Twig/Template.php(374): craft\web\twig\Template->display(Array)
#14 /var/www/www.moldejazz.no/vendor/twig/twig/lib/Twig/Environment.php(289): Twig_Template->render(Array)
#15 /var/www/www.moldejazz.no/vendor/craftcms/cms/src/web/View.php(308): Twig_Environment->render('_elements/table...', Array)
#16 /var/www/www.moldejazz.no/vendor/craftcms/cms/src/base/Element.php(446): craft\web\View->renderTemplate('_elements/table...', Array)
#17 /var/www/www.moldejazz.no/vendor/craftcms/cms/src/controllers/ElementIndexesController.php(391): craft\base\Element::indexHtml(Object(Solspace\Freeform\Elements\Db\SubmissionQuery), Array, Array, '*', 'index', true, true)
#18 /var/www/www.moldejazz.no/vendor/craftcms/cms/src/controllers/ElementIndexesController.php(119): craft\controllers\ElementIndexesController->_elementResponseData(true, true)
#19 [internal function]: craft\controllers\ElementIndexesController->actionGetElements()
#20 /var/www/www.moldejazz.no/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#21 /var/www/www.moldejazz.no/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#22 /var/www/www.moldejazz.no/vendor/craftcms/cms/src/web/Controller.php(80): yii\base\Controller->runAction('get-elements', Array)
#23 /var/www/www.moldejazz.no/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('get-elements', Array)
#24 /var/www/www.moldejazz.no/vendor/craftcms/cms/src/web/Application.php(240): yii\base\Module->runAction('element-indexes...', Array)
#25 /var/www/www.moldejazz.no/vendor/craftcms/cms/src/web/Application.php(450): craft\web\Application->runAction('element-indexes...', Array)
#26 /var/www/www.moldejazz.no/vendor/craftcms/cms/src/web/Application.php(211): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#27 /var/www/www.moldejazz.no/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#28 /var/www/www.moldejazz.no/web/index.php(21): yii\base\Application->run()
#29 {main}
```

```
$_POST = [
    'context' => 'index'
    'elementType' => 'Solspace\\Freeform\\Elements\\Submission'
    'source' => '*'
    'criteria' => [
        'status' => ''
        'siteId' => ''
        'search' => ''
        'limit' => '50'
        'enabledForSite' => ''
    ]
    'viewState' => [
        'mode' => 'table'
        'order' => 'dateCreated'
        'sort' => 'desc'
    ]
]
```

```
$_SESSION = [
    'bd62416aa8538ede709019a5e113eea5__flash' => [
        'freeform_submission_flash2' => -1
    ]
    '1031b8c41dfff97a311a7ac99863bdc5__id' => '1'
    '1031b8c41dfff97a311a7ac99863bdc5__expire' => 1518607862
    'freeformActiveSessions' => [
        1518603839 => '5KM0OK02p_e6264b6f5560d6b1e5b8d95baad6f02d822f2b685a840e3f77227'
        1518603885 => '5KM0OK02p_e6264b6f5560d6b1e5b8d95baad6f02d822f2b685a840e3f77227'
        1518603912 => '5KM0OK02p_e6264b6f5560d6b1e5b8d95baad6f02d822f2b685a840e3f77227'
    ]
    'freeformHoneypotHashList' => '[]'
    'freeform_submission_flash2' => true
]
```

**Comment by kjmartens** [comment]
Thanks for reporting this. It's related to an update in Craft 3 RC10. The next release will have this resolved. :)
