### ISSUE TITLE
Unable to delete submissions in control panel

### ISSUE THREAD

**Issue by icreatestuff** [solspace/craft3-freeform#194]
**Steps to reproduce**

1. From the `/freeform/submissions` page in the control panel I check one or more submissions and use the actions cog to 'Delete...'
2. I see a confirmation alert asking if I really want to delete the selected submissions. I click 'OK'.
3. The submissions aren't deleted.

Opening up Chrome devtools I can see a failed 500 network request to `/index.php?p=admin/actions/element-indexes/perform-action&v=1629822844688` which is returning an error "Class 'Freeform_Submission' not found".

Here's the stacktrace as found in the web.log file

```
2021-08-24 17:17:27 [-][1][-][error][Error] Error: Class 'Freeform_Submission' not found in /var/www/vhosts/examplesite.test/httpdocs/vendor/craftcms/cms/src/services/Elements.php:1457
Stack trace:
#0 /var/www/vhosts/examplesite.test/httpdocs/vendor/solspace/craft-freeform/packages/plugin/src/Services/SubmissionsService.php(354): craft\services\Elements->deleteElementById(3129)
#1 /var/www/vhosts/examplesite.test/httpdocs/vendor/solspace/craft-freeform/packages/plugin/src/Elements/Actions/DeleteSubmissionAction.php(46): Solspace\Freeform\Services\SubmissionsService->delete(Array)
#2 /var/www/vhosts/examplesite.test/httpdocs/vendor/craftcms/cms/src/controllers/ElementIndexesController.php(230): Solspace\Freeform\Elements\Actions\DeleteSubmissionAction->performAction(Object(Solspace\Freeform\Elements\Db\SubmissionQuery))
#3 [internal function]: craft\controllers\ElementIndexesController->actionPerformAction()
#4 /var/www/vhosts/examplesite.test/httpdocs/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#5 /var/www/vhosts/examplesite.test/httpdocs/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array)
#6 /var/www/vhosts/examplesite.test/httpdocs/vendor/craftcms/cms/src/web/Controller.php(190): yii\base\Controller->runAction('perform-action', Array)
#7 /var/www/vhosts/examplesite.test/httpdocs/vendor/yiisoft/yii2/base/Module.php(534): craft\web\Controller->runAction('perform-action', Array)
#8 /var/www/vhosts/examplesite.test/httpdocs/vendor/craftcms/cms/src/web/Application.php(274): yii\base\Module->runAction('element-indexes...', Array)
#9 /var/www/vhosts/examplesite.test/httpdocs/vendor/craftcms/cms/src/web/Application.php(577): craft\web\Application->runAction('element-indexes...', Array)
#10 /var/www/vhosts/examplesite.test/httpdocs/vendor/craftcms/cms/src/web/Application.php(253): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#11 /var/www/vhosts/examplesite.test/httpdocs/vendor/yiisoft/yii2/base/Application.php(392): craft\web\Application->handleRequest(Object(craft\web\Request))
#12 /var/www/vhosts/examplesite.test/httpdocs/web/index.php(24): yii\base\Application->run()
```

**Expected behavior**
The selected submissions should be deleted

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 3.6.12
- Freeform Version: 3.11.3
- Freeform Edition: Pro
- Fresh Install or Upgrade: Upgrade

Many thanks

**Comment by icreatestuff** [comment]
Hi @kjmartens thanks for the help, that was precisely the problem. Having updated the records in `craft_elements` I can now successfully delete the submissions from the control panel.

Many thanks,
Matt

**Comment by kjmartens** [comment]
Thanks @icreatestuff
