### ISSUE TITLE
Data too long for column - Select field value

### ISSUE THREAD

**Issue by alexjcollins** [solspace/craft3-freeform#228]
**Describe the bug or issue you're experiencing**
We have a client who is getting submissions errors due to the length of a `<select>` option value. In their case, the value that's failing is 133 characters, but I'm not sure what the actual limit is.

**Steps to reproduce**

1. Create a form with a select field
2. Ensure the option in the select field is 133 characters or more
3. Try to submit the form

**Expected behavior**

I'd expect either;

- the select to be able to handle longer values, or;
- the form UI present a validation error to the user letting them know the input option is too long

**Craft & Plugin Info (please complete the following information):**

- Craft Version: Craft Pro 3.6.17
- Freeform Version: 3.11.9
- Freeform Edition: Pro
- Fresh Install or Upgrade: Fresh

**Additional context**

Here's a stack trace from Sentry:

```
PDOException: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'field_80' at row 1
#19 /var/www/html/vendor/yiisoft/yii2/db/Command.php(1302): PDOStatement::execute
#18 /var/www/html/vendor/yiisoft/yii2/db/Command.php(1302): yii\db\Command::internalExecute
#17 /var/www/html/vendor/yiisoft/yii2/db/Command.php(1102): yii\db\Command::execute
#16 /var/www/html/vendor/solspace/craft-freeform/packages/plugin/src/Elements/Submission.php(497): Solspace\Freeform\Elements\Submission::afterSave
#15 /var/www/html/vendor/craftcms/cms/src/services/Elements.php(2514): craft\services\Elements::_saveElementInternal
#14 /var/www/html/vendor/craftcms/cms/src/services/Elements.php(758): craft\services\Elements::saveElement
#13 /var/www/html/vendor/solspace/craft-freeform/packages/plugin/src/Services/SubmissionsService.php(174): Solspace\Freeform\Services\SubmissionsService::storeSubmission
#12 /var/www/html/vendor/solspace/craft-freeform/packages/plugin/src/Library/Composer/Components/Form.php(1581): Solspace\Freeform\Library\Composer\Components\Form::saveStoredStateToDatabase
#11 /var/www/html/vendor/solspace/craft-freeform/packages/plugin/src/Library/Composer/Components/Form.php(790): Solspace\Freeform\Library\Composer\Components\Form::submit
#10 /var/www/html/vendor/solspace/craft-freeform/packages/plugin/src/Controllers/ApiController.php(69): Solspace\Freeform\Controllers\ApiController::actionForm
#9 [internal](0): call_user_func_array
#8 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): yii\base\InlineAction::runWithParams
#7 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\Controller::runAction
#6 /var/www/html/vendor/craftcms/cms/src/web/Controller.php(190): craft\web\Controller::runAction
#5 /var/www/html/vendor/yiisoft/yii2/base/Module.php(534): yii\base\Module::runAction
#4 /var/www/html/vendor/craftcms/cms/src/web/Application.php(278): craft\web\Application::runAction
#3 /var/www/html/vendor/craftcms/cms/src/web/Application.php(581): craft\web\Application::_processActionRequest
#2 /var/www/html/vendor/craftcms/cms/src/web/Application.php(257): craft\web\Application::handleRequest
#1 /var/www/html/vendor/yiisoft/yii2/base/Application.php(392): yii\base\Application::run
#0 /index.php(22): null
yii\db\Exception: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'field_80' at row 1
The SQL being executed was: INSERT INTO `freeform_submissions` ( XXX REDACTED XXX )
#19 /var/www/html/vendor/yiisoft/yii2/db/Schema.php(678): yii\db\Schema::convertException
#18 /var/www/html/vendor/yiisoft/yii2/db/Command.php(1307): yii\db\Command::internalExecute
#17 /var/www/html/vendor/yiisoft/yii2/db/Command.php(1102): yii\db\Command::execute
#16 /var/www/html/vendor/solspace/craft-freeform/packages/plugin/src/Elements/Submission.php(497): Solspace\Freeform\Elements\Submission::afterSave
#15 /var/www/html/vendor/craftcms/cms/src/services/Elements.php(2514): craft\services\Elements::_saveElementInternal
#14 /var/www/html/vendor/craftcms/cms/src/services/Elements.php(758): craft\services\Elements::saveElement
#13 /var/www/html/vendor/solspace/craft-freeform/packages/plugin/src/Services/SubmissionsService.php(174): Solspace\Freeform\Services\SubmissionsService::storeSubmission
#12 /var/www/html/vendor/solspace/craft-freeform/packages/plugin/src/Library/Composer/Components/Form.php(1581): Solspace\Freeform\Library\Composer\Components\Form::saveStoredStateToDatabase
#11 /var/www/html/vendor/solspace/craft-freeform/packages/plugin/src/Library/Composer/Components/Form.php(790): Solspace\Freeform\Library\Composer\Components\Form::submit
#10 /var/www/html/vendor/solspace/craft-freeform/packages/plugin/src/Controllers/ApiController.php(69): Solspace\Freeform\Controllers\ApiController::actionForm
#9 [internal](0): call_user_func_array
#8 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): yii\base\InlineAction::runWithParams
#7 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\Controller::runAction
#6 /var/www/html/vendor/craftcms/cms/src/web/Controller.php(190): craft\web\Controller::runAction
#5 /var/www/html/vendor/yiisoft/yii2/base/Module.php(534): yii\base\Module::runAction
#4 /var/www/html/vendor/craftcms/cms/src/web/Application.php(278): craft\web\Application::runAction
#3 /var/www/html/vendor/craftcms/cms/src/web/Application.php(581): craft\web\Application::_processActionRequest
#2 /var/www/html/vendor/craftcms/cms/src/web/Application.php(257): craft\web\Application::handleRequest
#1 /var/www/html/vendor/yiisoft/yii2/base/Application.php(392): yii\base\Application::run
#0 /index.php(22): null
```

**Comment by kjmartens** [comment]
Sorry for the trouble @alexjcollins. This is because the default character limit for the Select field type is `100`. In Freeform 3.12+ (currently in beta) this has been increased (for new fields) to `255`. You can adjust this for your site now by opening up the `freeform_submissions` database table and change the _Type_ of that field from `VARCHAR(100)` to `VARCHAR(255)`. If you need any more characters than that, you can switch it to `TEXT` instead. 🙂
