### ISSUE TITLE
Error Installing: Syntax error or access violation

### ISSUE THREAD

**Issue by davist11** [solspace/craft3-freeform#29]
I'm getting an error trying to install Freeform Lite on a site that was just updated from Craft 2.

```
Database Exception: SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP 'craft_freeform_crm_fields_integrationId_fk'; check that column/key exists
The SQL being executed was: ALTER TABLE craft_freeform_crm_fields DROP FOREIGN KEY craft_freeform_crm_fields_integrationId_fk

Migration: Solspace\Freeform\migrations\m180120_140521_CraftUpgrade

Output:

> drop foreign key craft_freeform_crm_fields_integrationId_fk from table {{%freeform_crm_fields}} ...Exception: SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP 'craft_freeform_crm_fields_integrationId_fk'; check that column/key exists
The SQL being executed was: ALTER TABLE craft_freeform_crm_fields DROP FOREIGN KEY craft_freeform_crm_fields_integrationId_fk (/Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/db/Schema.php:664)
#0 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/db/Command.php(1263): yii\db\Schema->convertException(Object(PDOException), 'ALTER TABLE cr...')
#1 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/db/Command.php(1075): yii\db\Command->internalExecute('ALTER TABLE cr...')
#2 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/db/Migration.php(479): yii\db\Command->execute()
#3 /Users/tdavis/sites/hamilton/vendor/solspace/craft3-freeform/src/migrations/m180120_140521_CraftUpgrade.php(45): yii\db\Migration->dropForeignKey('craft_freeform_...', '{{%freeform_crm...')
#4 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/db/Migration.php(42): Solspace\Freeform\migrations\m180120_140521_CraftUpgrade->safeUp()
#5 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/db/MigrationManager.php(243): craft\db\Migration->up(true)
#6 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/db/MigrationManager.php(163): craft\db\MigrationManager->migrateUp(Object(Solspace\Freeform\migrations\m180120_140521_CraftUpgrade))
#7 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/services/Updates.php(219): craft\db\MigrationManager->up()
#8 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/controllers/BaseUpdaterController.php(435): craft\services\Updates->runMigrations(Array)
#9 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/controllers/UpdaterController.php(207): craft\controllers\BaseUpdaterController->runMigrations(Array, 'restore-db')
#10 [internal function]: craft\controllers\UpdaterController->actionMigrate()
#11 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#12 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#13 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/web/Controller.php(74): yii\base\Controller->runAction('migrate', Array)
#14 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('migrate', Array)
#15 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/web/Application.php(237): yii\base\Module->runAction('updater/migrate', Array)
#16 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/web/Application.php(546): craft\web\Application->runAction('updater/migrate')
#17 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/web/Application.php(191): craft\web\Application->_processUpdateLogic(Object(craft\web\Request))
#18 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#19 /Users/tdavis/sites/hamilton/public/index.php(21): yii\base\Application->run()
#20 {main}
```

**Comment by kjmartens** [comment]
Sorry for the trouble...
When you say you're installing Freeform Lite on your Craft 3 site that was updated from Craft 2, did you have Freeform installed from before, on the Craft 2? And was it Freeform Lite or Freeform Pro?

**Comment by gustavs-gutmanis** [comment]
Could you also let us know which version of Freeform you had installed on the Craft 2 installation?
Thank you.

**Comment by davist11** [comment]
Yes, we had Freeform Pro installed for Craft 2.

**Comment by kjmartens** [comment]
@davist11 which version number of Freeform Pro did you have installed for Craft 2? :)

**Comment by davist11** [comment]
I ended up having to revert back to a Craft 2 DB because of some Commerce migration errors. Should I try to enable Freeform again? Should I be doing Lite or Pro? Both?

**Comment by kjmartens** [comment]
We just released Freeform 2 Beta 12, which might fix this. Combined with the Beta 6 release of Calendar 2, can you try running a full upgrade from Freeform 1 -> 2 and Calendar 1 -> 2 again? Sorry for all the trouble.

**Comment by davist11** [comment]
😬

Different error when trying to enable Freeform Lite:

```
Database Exception: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'fileCount' in 'field list'
The SQL being executed was: SELECT id, type, notificationId, value, values, placeholder, options, checked, fileKinds, rows, maxFileSizeKB, fileCount, additionalProperties, assetSourceId
FROM craft_freeform_fields

Migration: Solspace\Freeform\migrations\m180120_140521_CraftUpgrade

Output:

> add column formTemplateId int unsigned to table {{%freeform_forms}} ... done (time: 0.035s)
> drop foreign key craft_freeform_crm_fields_integrationId_fk from table {{%freeform_crm_fields}} ... done (time: 0.018s)
> drop foreign key craft_freeform_export_profiles_formId_fk from table {{%freeform_export_profiles}} ... done (time: 0.016s)
> drop foreign key craft_freeform_export_settings_userId_fk from table {{%freeform_export_settings}} ... done (time: 0.026s)
> drop foreign key craft_freeform_fields_notificationId_fk from table {{%freeform_fields}} ... done (time: 0.016s)
> drop foreign key craft_freeform_mailing_list_fields_mailingListId_fk from table {{%freeform_mailing_list_fields}} ... done (time: 0.026s)
> drop foreign key craft_freeform_mailing_lists_integrationId_fk from table {{%freeform_mailing_lists}} ... done (time: 0.020s)
> drop foreign key craft_freeform_submissions_id_fk from table {{%freeform_submissions}} ... done (time: 0.017s)
> drop foreign key craft_freeform_submissions_statusId_fk from table {{%freeform_submissions}} ... done (time: 0.026s)
> drop foreign key craft_freeform_submissions_formId_fk from table {{%freeform_submissions}} ... done (time: 0.016s)
> add foreign key crm_fields_integrationId: {{%freeform_crm_fields}} (integrationId) references {{%freeform_integrations}} (id) ... done (time: 0.019s)
> add foreign key mailing_list_fields_mailingListId: {{%freeform_mailing_list_fields}} (mailingListId) references {{%freeform_mailing_lists}} (id) ... done (time: 0.020s)
> add foreign key mailing_lists_integrationId: {{%freeform_mailing_lists}} (integrationId) references {{%freeform_integrations}} (id) ... done (time: 0.021s)
> add foreign key submissions_id_fk: {{%freeform_submissions}} (id) references {{%elements}} (id) ... done (time: 0.022s)
> add foreign key submissions_formId_fk: {{%freeform_submissions}} (formId) references {{%freeform_forms}} (id) ... done (time: 0.024s)
> add foreign key submissions_statusId_fk: {{%freeform_submissions}} (statusId) references {{%freeform_statuses}} (id) ... done (time: 0.025s)
> rename table {{%freeform_export_profiles}} to {{%freeform_export_profiles_backup}} ... done (time: 0.002s)
> rename table {{%freeform_export_settings}} to {{%freeform_export_settings_backup}} ... done (time: 0.002s)
> add column metaProperties text default null after assetSourceId to table {{%freeform_fields}} ... done (time: 0.026s)
Exception: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'fileCount' in 'field list'
The SQL being executed was: SELECT id, type, notificationId, value, values, placeholder, options, checked, fileKinds, rows, maxFileSizeKB, fileCount, additionalProperties, assetSourceId
FROM craft_freeform_fields (/Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/db/Schema.php:664)
#0 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/db/Command.php(1263): yii\db\Schema->convertException(Object(PDOException), 'SELECT id, t...')
#1 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/db/Command.php(1148): yii\db\Command->internalExecute('SELECT id, t...')
#2 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/db/Command.php(399): yii\db\Command->queryInternal('fetchAll', NULL)
#3 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/db/Query.php(237): yii\db\Command->queryAll()
#4 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/db/Query.php(155): yii\db\Query->all(NULL)
#5 /Users/tdavis/sites/hamilton/vendor/solspace/craft3-freeform/src/migrations/m180120_140521_CraftUpgrade.php(142): craft\db\Query->all()
#6 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/db/Migration.php(42): Solspace\Freeform\migrations\m180120_140521_CraftUpgrade->safeUp()
#7 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/db/MigrationManager.php(243): craft\db\Migration->up(true)
#8 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/db/MigrationManager.php(163): craft\db\MigrationManager->migrateUp(Object(Solspace\Freeform\migrations\m180120_140521_CraftUpgrade))
#9 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/services/Updates.php(212): craft\db\MigrationManager->up()
#10 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/controllers/BaseUpdaterController.php(435): craft\services\Updates->runMigrations(Array)
#11 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/controllers/UpdaterController.php(207): craft\controllers\BaseUpdaterController->runMigrations(Array, 'restore-db')
#12 [internal function]: craft\controllers\UpdaterController->actionMigrate()
#13 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#14 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#15 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/web/Controller.php(74): yii\base\Controller->runAction('migrate', Array)
#16 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('migrate', Array)
#17 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/web/Application.php(237): yii\base\Module->runAction('updater/migrate', Array)
#18 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/web/Application.php(546): craft\web\Application->runAction('updater/migrate')
#19 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/web/Application.php(191): craft\web\Application->_processUpdateLogic(Object(craft\web\Request))
#20 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#21 /Users/tdavis/sites/hamilton/public/index.php(21): yii\base\Application->run()
#22 {main}
```

**Comment by kjmartens** [comment]
This should be corrected in the next version of Freeform (beta 13). You'll need to re-run the migration however.
