### ISSUE TITLE
Site crash: Getting unknown property: Solspace\Freeform\Models\Settings::bypassSpamCheckOnLoggedInUsers

### ISSUE THREAD

**Issue by incraigulous** [solspace/craft3-freeform#301]
After updating our site to the latest version of freeform our form pages stopped working. We restored a backup of our server, and our whole site crashed. After the site crashed, it gives the following error:

```
yii\base\UnknownPropertyException: Getting unknown property: Solspace\Freeform\Models\Settings::bypassSpamCheckOnLoggedInUsers in /home/customer/www/captulsa.org/captulsa.org/releases/20210917141028/vendor/yiisoft/yii2/base/Component.php:154
Stack trace:
#0 /home/customer/www/captulsa.org/captulsa.org/releases/20210917141028/vendor/solspace/craft-freeform/packages/plugin/src/Bundles/Captchas/ReCaptcha.php(29): yii\base\Component->__get('bypassSpamCheck...')
#1 [internal function]: Solspace\Freeform\Bundles\Captchas\ReCaptcha->__construct()
#2 /home/customer/www/captulsa.org/captulsa.org/releases/20210917141028/vendor/solspace/craft-freeform/packages/plugin/src/Freeform.php(1116): ReflectionClass->newInstance()
#3 /home/customer/www/captulsa.org/captulsa.org/releases/20210917141028/vendor/solspace/craft-freeform/packages/plugin/src/Freeform.php(300): Solspace\Freeform\Freeform->initBundles()
#4 /home/customer/www/captulsa.org/captulsa.org/releases/20210917141028/vendor/yiisoft/yii2/base/BaseObject.php(109): Solspace\Freeform\Freeform->init()
#5 /home/customer/www/captulsa.org/captulsa.org/releases/20210917141028/vendor/yiisoft/yii2/base/Module.php(161): yii\base\BaseObject->__construct(Array)
#6 /home/customer/www/captulsa.org/captulsa.org/releases/20210917141028/vendor/craftcms/cms/src/base/Plugin.php(115): yii\base\Module->__construct('freeform', Object(craft\web\Application), Array)
#7 [internal function]: craft\base\Plugin->__construct('freeform', Object(craft\web\Application), Array)
#8 /home/customer/www/captulsa.org/captulsa.org/releases/20210917141028/vendor/yiisoft/yii2/di/Container.php(419): ReflectionClass->newInstanceArgs(Array)
#9 /home/customer/www/captulsa.org/captulsa.org/releases/20210917141028/vendor/yiisoft/yii2/di/Container.php(170): yii\di\Container->build('Solspace\\Freefo...', Array, Array)
#10 /home/customer/www/captulsa.org/captulsa.org/releases/20210917141028/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get('Solspace\\Freefo...', Array, Array)
#11 /home/customer/www/captulsa.org/captulsa.org/releases/20210917141028/vendor/craftcms/cms/src/Craft.php(66): yii\BaseYii::createObject(Array, Array)
#12 /home/customer/www/captulsa.org/captulsa.org/releases/20210917141028/vendor/craftcms/cms/src/services/Plugins.php(945): Craft::createObject(Array, Array)
#13 /home/customer/www/captulsa.org/captulsa.org/releases/20210917141028/vendor/craftcms/cms/src/services/Plugins.php(229): craft\services\Plugins->createPlugin('freeform', Array)
#14 /home/customer/www/captulsa.org/captulsa.org/releases/20210917141028/vendor/craftcms/cms/src/base/ApplicationTrait.php(1487): craft\services\Plugins->loadPlugins()
#15 /home/customer/www/captulsa.org/captulsa.org/releases/20210917141028/vendor/craftcms/cms/src/web/Application.php(93): craft\web\Application->_postInit()
#16 /home/customer/www/captulsa.org/captulsa.org/releases/20210917141028/vendor/yiisoft/yii2/base/BaseObject.php(109): craft\web\Application->init()
#17 /home/customer/www/captulsa.org/captulsa.org/releases/20210917141028/vendor/yiisoft/yii2/base/Application.php(204): yii\base\BaseObject->__construct(Array)
#18 [internal function]: yii\base\Application->__construct(Array)
#19 /home/customer/www/captulsa.org/captulsa.org/releases/20210917141028/vendor/yiisoft/yii2/di/Container.php(419): ReflectionClass->newInstanceArgs(Array)
#20 /home/customer/www/captulsa.org/captulsa.org/releases/20210917141028/vendor/yiisoft/yii2/di/Container.php(170): yii\di\Container->build('craft\\web\\Appli...', Array, Array)
#21 /home/customer/www/captulsa.org/captulsa.org/releases/20210917141028/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get('craft\\web\\Appli...', Array, Array)
#22 /home/customer/www/captulsa.org/captulsa.org/releases/20210917141028/vendor/craftcms/cms/src/Craft.php(66): yii\BaseYii::createObject(Array, Array)
#23 /home/customer/www/captulsa.org/captulsa.org/releases/20210917141028/vendor/craftcms/cms/bootstrap/bootstrap.php(242): Craft::createObject(Array)
#24 /home/customer/www/captulsa.org/captulsa.org/releases/20210917141028/vendor/craftcms/cms/bootstrap/web.php(51): require('/home/customer/...')
#25 /home/customer/www/captulsa.org/captulsa.org/releases/20210917141028/web/index.php(25): require('/home/customer/...')
#26 {main}
```

**Steps to reproduce**

1. Update freeform to >= 3.12.13

**Expected behavior**

The plugin does not throw errors.

**Craft & Plugin Info (please complete the following information):**

- Craft Version: Craft Pro 3.7.28
- Freeform Version: 3.12.13
- Freeform Edition: Pro
- Fresh Install or Upgrade: Existing install 

**Additional context**

**Comment by incraigulous** [comment]
I've resolved the issue by installing craft and freeform to the last version via the CLI. I suspect we ran into this issue during the GUI craft upgrade: https://github.com/solspace/craft3-freeform/issues/302. After restoring our site to an earlier version and upgrading to the lastest version via CLI, it's now working.

**Comment by kjmartens** [comment]
Thanks for the update @incraigulous. Glad it's working now. Definitely better to update via CLI vs CP. 🙂
