### ISSUE TITLE
Cannot create a new field via the "Fields" page - Twig Template Loading Error

### ISSUE THREAD

**Issue by wei2go** [solspace/craft3-freeform#320]
**Describe the bug or issue you're experiencing**
Twig Template Loading Error – craft\web\twig\TemplateLoaderException
Unable to find the template “freeform/fields/_types/password” in "freeform/fields/edit" at line 108.

[error][craft\web\twig\TemplateLoaderException] craft\web\twig\TemplateLoaderException: Unable to find the template “freeform/fields/_types/password” in "freeform/fields/edit" at line 108. in \vendor\craftcms\cms\src\web\twig\TemplateLoader.php:116
Stack trace:
#0 \vendor\craftcms\cms\src\web\twig\TemplateLoader.php(72): craft\web\twig\TemplateLoader->_resolveTemplate('freeform/fields...')
#1 \vendor\twig\twig\src\Environment.php(299): craft\web\twig\TemplateLoader->getCacheKey('freeform/fields...')
#2 \vendor\twig\twig\src\Environment.php(381): Twig\Environment->getTemplateClass('freeform/fields...')
#3 \vendor\craftcms\cms\src\web\twig\Environment.php(41): Twig\Environment->loadTemplate('freeform/fields...', NULL)
#4 \vendor\twig\twig\src\Template.php(333): craft\web\twig\Environment->loadTemplate('freeform/fields...', NULL)
#5 \storage\runtime\compiled_templates\36\36ad9e3e3fde47b8d2fb4a511c102892982c893454fdde75ebeb66c47886ca8a.php(212): Twig\Template->loadTemplate('freeform/fields...', 'freeform/fields...', 108)

Other facts:
- The issue persists after clearing craft cache and invalidating template cache.
- The form builder screen works fine when adding a new field from there.
- Craft version: 3.7.36
- Tried a fresh composer install (by removing the vendor folder), and the issue persists.

**Steps to reproduce**

1. Go to CP: Freeform -> Fields
2. Click "+ New Field"
3. It triggers an error, so I can't proceed further.

**Expected behavior**
Able to create fields via this page.

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 3.7.36
- Freeform Version: 3.13.4
- Freeform Edition: Pro
- Fresh Install or Upgrade: Upgrade

**Additional context**
- The issue persists after clearing craft cache and invalidating template cache.
- The form builder screen works fine when adding a new field from there.
- Double checked the Pro license in Craft ID, which is valid.
- Tried a fresh composer install (by removing the vendor folder), and the issue persists.

**Comment by wei2go** [comment]
nvm. This has been fixed after updating Freeform to the latest. I believe it has been fixed in 3.13.5?
