### ISSUE TITLE
Column not found: 1054 Unknown column 'fileCount'

### ISSUE THREAD

**Issue by joshua-martin** [solspace/craft3-freeform#33]
Upgrading from Craft CMS 2.6.3012 / Freeform Pro 1.8.6 to Craft CMS 3.0.0-RC15.

I'm trying to install Freeform Lite from the Plugin store, composer dependencies install correctly, but database update fails. 

```
Database Exception: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'fileCount' in 'field list'
The SQL being executed was: SELECT id, type, notificationId, value, values, placeholder, options, checked, fileKinds, rows, maxFileSizeKB, fileCount, additionalProperties, assetSourceId
FROM craft_freeform_fields

Migration: Solspace\Freeform\migrations\m180120_140521_CraftUpgrade

Output:

> add column formTemplateId int unsigned to table {{%freeform_forms}} ... done (time: 0.101s)
> drop foreign key craft_freeform_crm_fields_integrationId_fk from table {{%freeform_crm_fields}} ... done (time: 0.294s)
> drop foreign key craft_freeform_export_profiles_formId_fk from table {{%freeform_export_profiles}} ... done (time: 0.124s)
> drop foreign key craft_freeform_export_settings_userId_fk from table {{%freeform_export_settings}} ... done (time: 0.201s)
> drop foreign key craft_freeform_fields_notificationId_fk from table {{%freeform_fields}} ... done (time: 0.190s)
> drop foreign key craft_freeform_mailing_list_fields_mailingListId_fk from table {{%freeform_mailing_list_fields}} ... done (time: 0.201s)
> drop foreign key craft_freeform_mailing_lists_integrationId_fk from table {{%freeform_mailing_lists}} ... done (time: 0.192s)
> drop foreign key craft_freeform_submissions_id_fk from table {{%freeform_submissions}} ... done (time: 0.191s)
> drop foreign key craft_freeform_submissions_statusId_fk from table {{%freeform_submissions}} ... done (time: 0.179s)
> drop foreign key craft_freeform_submissions_formId_fk from table {{%freeform_submissions}} ... done (time: 0.201s)
> add foreign key crm_fields_integrationId: {{%freeform_crm_fields}} (integrationId) references {{%freeform_integrations}} (id) ... done (time: 0.189s)
> add foreign key mailing_list_fields_mailingListId: {{%freeform_mailing_list_fields}} (mailingListId) references {{%freeform_mailing_lists}} (id) ... done (time: 0.169s)
> add foreign key mailing_lists_integrationId: {{%freeform_mailing_lists}} (integrationId) references {{%freeform_integrations}} (id) ... done (time: 0.189s)
> add foreign key submissions_id_fk: {{%freeform_submissions}} (id) references {{%elements}} (id) ... done (time: 0.191s)
> add foreign key submissions_formId_fk: {{%freeform_submissions}} (formId) references {{%freeform_forms}} (id) ... done (time: 0.241s)
> add foreign key submissions_statusId_fk: {{%freeform_submissions}} (statusId) references {{%freeform_statuses}} (id) ... done (time: 0.307s)
> rename table {{%freeform_export_profiles}} to {{%freeform_export_profiles_backup}} ... done (time: 0.006s)
> rename table {{%freeform_export_settings}} to {{%freeform_export_settings_backup}} ... done (time: 0.005s)
> add column metaProperties text default null after assetSourceId to table {{%freeform_fields}} ... done (time: 0.127s)
Exception: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'fileCount' in 'field list'
The SQL being executed was: SELECT id, type, notificationId, value, values, placeholder, options, checked, fileKinds, rows, maxFileSizeKB, fileCount, additionalProperties, assetSourceId
FROM craft_freeform_fields (/Users/joshuamartin/Documents/Websites/vanilla-craft3/vendor/yiisoft/yii2/db/Schema.php:664)
#0 /Users/joshuamartin/Documents/Websites/vanilla-craft3/vendor/yiisoft/yii2/db/Command.php(1263): yii\db\Schema->convertException(Object(PDOException), 'SELECT id, t...')
#1 /Users/joshuamartin/Documents/Websites/vanilla-craft3/vendor/yiisoft/yii2/db/Command.php(1148): yii\db\Command->internalExecute('SELECT id, t...')
#2 /Users/joshuamartin/Documents/Websites/vanilla-craft3/vendor/yiisoft/yii2/db/Command.php(399): yii\db\Command->queryInternal('fetchAll', NULL)
#3 /Users/joshuamartin/Documents/Websites/vanilla-craft3/vendor/yiisoft/yii2/db/Query.php(237): yii\db\Command->queryAll()
#4 /Users/joshuamartin/Documents/Websites/vanilla-craft3/vendor/craftcms/cms/src/db/Query.php(136): yii\db\Query->all(NULL)
#5 /Users/joshuamartin/Documents/Websites/vanilla-craft3/vendor/solspace/craft3-freeform/src/migrations/m180120_140521_CraftUpgrade.php(142): craft\db\Query->all()
#6 /Users/joshuamartin/Documents/Websites/vanilla-craft3/vendor/craftcms/cms/src/db/Migration.php(42): Solspace\Freeform\migrations\m180120_140521_CraftUpgrade->safeUp()
#7 /Users/joshuamartin/Documents/Websites/vanilla-craft3/vendor/craftcms/cms/src/db/MigrationManager.php(243): craft\db\Migration->up(true)
#8 /Users/joshuamartin/Documents/Websites/vanilla-craft3/vendor/craftcms/cms/src/db/MigrationManager.php(163): craft\db\MigrationManager->migrateUp(Object(Solspace\Freeform\migrations\m180120_140521_CraftUpgrade))
#9 /Users/joshuamartin/Documents/Websites/vanilla-craft3/vendor/craftcms/cms/src/services/Updates.php(219): craft\db\MigrationManager->up()
#10 /Users/joshuamartin/Documents/Websites/vanilla-craft3/vendor/craftcms/cms/src/controllers/BaseUpdaterController.php(435): craft\services\Updates->runMigrations(Array)
#11 /Users/joshuamartin/Documents/Websites/vanilla-craft3/vendor/craftcms/cms/src/controllers/UpdaterController.php(207): craft\controllers\BaseUpdaterController->runMigrations(Array, 'restore-db')
#12 [internal function]: craft\controllers\UpdaterController->actionMigrate()
#13 /Users/joshuamartin/Documents/Websites/vanilla-craft3/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#14 /Users/joshuamartin/Documents/Websites/vanilla-craft3/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#15 /Users/joshuamartin/Documents/Websites/vanilla-craft3/vendor/craftcms/cms/src/web/Controller.php(74): yii\base\Controller->runAction('migrate', Array)
#16 /Users/joshuamartin/Documents/Websites/vanilla-craft3/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('migrate', Array)
#17 /Users/joshuamartin/Documents/Websites/vanilla-craft3/vendor/craftcms/cms/src/web/Application.php(237): yii\base\Module->runAction('updater/migrate', Array)
#18 /Users/joshuamartin/Documents/Websites/vanilla-craft3/vendor/craftcms/cms/src/web/Application.php(546): craft\web\Application->runAction('updater/migrate')
#19 /Users/joshuamartin/Documents/Websites/vanilla-craft3/vendor/craftcms/cms/src/web/Application.php(191): craft\web\Application->_processUpdateLogic(Object(craft\web\Request))
#20 /Users/joshuamartin/Documents/Websites/vanilla-craft3/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#21 /Users/joshuamartin/Documents/Websites/vanilla-craft3/web/index.php(21): yii\base\Application->run()
#22 {main}
```

**Comment by joshua-martin** [comment]
Closing as [issue looks to be already reported](https://github.com/solspace/craft3-freeform/issues/29#issuecomment-375805914) on #29.

**Comment by kjmartens** [comment]
This should be corrected in the next version of Freeform (beta 13).
